name: money_field
description: A simple to use TextEditingController for handling money values.
version: 1.0.0
author: Eric Grandt
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: